
- name: Disable Zero Configuration Network
  become: true
  lineinfile: dest=/etc/sysconfig/network
              regexp=''
              insertafter=EOF
              line='NOZEROCONF=yes'
  notify:
  - restart network

- name: Disable NetworkManager
  become: true
  systemd: name=NetworkManager state=stopped enabled=no

- name: Disable Firewalld
  become: true
  systemd: name=firewalld state=stopped enabled=no
  register: result

# - name: check if killed
#   debug: msg="{{ killed.changed }}"


- name: Create vlan and dummy interfaces
  become: true
  template: src=templates/ifcfg.j2 dest=/etc/sysconfig/network-scripts/ifcfg-{{ item.device }} mode=0644 owner=root group=root
  with_items:
  - "{{ interfaces }}"
  notify:
  - restart network


