---
- name: remove default route created with vagrant
  become: true
  lineinfile: dest=/etc/sysconfig/network-scripts/ifcfg-enp0s3
              regexp='^DEFROUTE='
              insertafter=EOF
              line='DEFROUTE=no'
  notify:
  - restart network
  when: (edge is not defined and edge != True)
  tags: quagga

- name: Enable quagga
  become: true
  systemd: name={{ item }} state=started enabled=yes
  with_items:
  - zebra
  - ospfd
  tags: quagga
  
- name: Create ospfd.conf
  become: true
  template: src=templates/ospfd.j2 dest=/etc/quagga/ospfd.conf mode=0644 owner=quagga group=quagga
  notify:
  - restart quagga
  tags: quagga



