---
- name: install iptables-services
    yum:
    name: iptables-services
    state: present

- name: Enable iptables
    systemd: name=iptables state=started enabled=yes

- name: Create rules
    command: iptables {{ item }}
  notify: save rules
  with_items:
  - "-P INPUT ACCEPT"  
  - "-F"  
  - "-t nat -F"  
  - "-A INPUT -i lo -j ACCEPT"
  - "-A INPUT -i enp0s3 -p tcp -m tcp --dport 22 -j ACCEPT"
  - "-A INPUT -i enp0s8 -p tcp -m tcp --dport 22 -j ACCEPT"
  - "-A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT"
  - "-A INPUT -p ospf -j ACCEPT"
  - "-A INPUT -i enp0s9.2 -p tcp -m tcp --dport 53 -j ACCEPT"
  - "-A INPUT -i enp0s9.2 -p udp -m udp --dport 53 -j ACCEPT"
  - "-A FORWARD -i enp0s9.2 -o enp0s3 -j ACCEPT"
  - "-A FORWARD -i enp0s3 -m state --state RELATED,ESTABLISHED -j ACCEPT"
  - "-A FORWARD -i enp0s3 -o enp0s9.2 -j REJECT --reject-with icmp-port-unreachable"
  - "-A OUTPUT -p tcp -m tcp --sport 22 -j ACCEPT"
  - "-A OUTPUT -p ospf -j ACCEPT"
  - "-t nat -A POSTROUTING -o enp0s3 -j MASQUERADE"
  - "-P INPUT DROP"  