---
- name: install iptables-services
  become: true
  yum:
    name: iptables-services
    state: present

- name: Enable iptables
  become: true
  systemd: name=iptables state=started enabled=yes

- name: Create rules
  become: true
  command: iptables {{ item }}
  notify: save rules
  with_items:
  - "-P INPUT ACCEPT"  
  - "-F"  
  - "-t nat -F"  
  - "-A INPUT -i lo -j ACCEPT"
  - "-A INPUT -i eth0 -p tcp -m tcp --dport 22 -j ACCEPT"
  - "-A INPUT -i eth1 -p tcp -m tcp --dport 22 -j ACCEPT"
  - "-A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT"
  - "-A INPUT -p ospf -j ACCEPT"
  - "-A INPUT -i eth2.2 -p tcp -m tcp --dport 53 -j ACCEPT"
  - "-A INPUT -i eth2.2 -p udp -m udp --dport 53 -j ACCEPT"
  - "-A FORWARD -i eth2.2 -o eth0 -j ACCEPT"
  - "-A FORWARD -i eth0 -m state --state RELATED,ESTABLISHED -j ACCEPT"
  - "-A FORWARD -i eth0 -o eth2.2 -j REJECT --reject-with icmp-port-unreachable"
  - "-A OUTPUT -p tcp -m tcp --sport 22 -j ACCEPT"
  - "-A OUTPUT -p ospf -j ACCEPT"
  - "-t nat -A POSTROUTING -o eth0 -j MASQUERADE"
  - "-P INPUT DROP"  