---
- name: Install nginx repo
  template: src={{ item.j2 }} dest={{ item.dst }} owner={{ item.owner }} group={{ item.group }} mode=0644
  with_items:
  - {j2: "templates/nginx.repo.j2", dst: "/etc/yum.repos.d/nginx.repo", owner: root, group: root}
  tags: hw


- name: install services
  yum: name={{ item }} state=installed
  with_items: 
  - httpd
  - nginx
  tags: hw

- name: Create site DocRoot
  file: 
    path: "{{ item }}"
    state: directory
    owner: apache
    group: apache
    mode: 0755
  with_items:
    - "{{ apache.site1.docroot }}"
    - "{{ apache.site2.docroot }}"
  tags: hw

- name: add 127.0.0.2
  lineinfile:
    path: /etc/sysconfig/network-scripts/ifcfg-lo
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
    insertafter: EOF
    #backrefs: yes
    backup: yes
  with_items:
  - { regexp: '^IPADDR1=', line: 'IPADDR1=127.0.0.2' }
  - { regexp: '^NETMASK1=', line: 'NETMASK1=255.0.0.0'}
  - { regexp: '^NETWORK1=', line: 'NETWORK1=127.0.0.0'}
  notify:
    - iface donwup
  tags: hw

- name: Change listen port
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
    insertafter: EOF
    #backrefs: yes
    backup: yes
  with_items:
  - { regexp: '^Listen', line: 'Listen 8080' }
  notify:
    - apache restart
  tags: hw

- name: Install config and files
  template: src={{ item.j2 }} dest={{ item.dst }} owner={{ item.owner }} group={{ item.group }} mode=0644
  with_items:
  - {j2: "templates/index.html.j2", dst: "{{ apache.site1.docroot }}/index.html", data: "1", owner: root, group: root}
  - {j2: "templates/index.html.j2", dst: "{{ apache.site2.docroot }}/index.html", data: "2", owner: root, group: root}
  - {j2: "templates/text.txt.j2", dst: "{{ apache.site1.docroot }}/text.txt", data: "1", owner: root, group: root}
  - {j2: "templates/text.txt.j2", dst: "{{ apache.site2.docroot }}/text.txt", data: "2", owner: root, group: root}
  - {j2: "templates/sites_apache.conf.j2", dst: "/etc/httpd/conf.d/sites.conf", data: "2", owner: root, group: root}
  - {j2: "templates/sites_nginx.conf.j2", dst: "/etc/nginx/conf.d/sites.conf", data: "2", owner: root, group: root}
  notify:
    - apache restart
    - nginx restart
  tags: hw

- name: Remove nginx default.conf
  file: path=/etc/nginx/conf.d/default.conf state=absent
  tags: hw

- name: Enable servers
  systemd: name={{ item }} state=started enabled=true
  with_items: 
  - httpd
  - nginx
  tags: hw

