---
- hosts: all
  become: true
  gather_facts: yes
  roles:
    - common
    - ntp

- hosts: dummy
  become: true
  roles:
    - dummy

- hosts: routers
  roles:
    - forward

- hosts: r0
  become: true
  vars:
  - edge: yes
  - dns_type: master
  - interfaces: 
    - {device: "enp0s9.2", ip: "10.2.2.1", net: "10.2.2.0", prefix: 24, vlan: 2, area: 0 }
  roles:
  - networking
  - quagga
  - edgefw
  - named
  - top-secure
  - pam_script

- hosts: r1
  become: true
  vars:
  - bfdneigh:
    - {ip: "10.4.4.10"}
    - {ip: "10.4.4.20"}
  - interfaces: 
    - {device: "enp0s9.2", ip: "10.2.2.254", net: "10.2.2.0", prefix: 24, vlan: 2, area: 0 }
    - {device: "enp0s10.4", ip: "10.4.4.254", net: "10.4.4.0", prefix: 24, vlan: 4, area: 1, bfd: yes }
  roles:
  - networking
  - quagga
  #- knockssh
  - openbfdd
  #- gauth
  - top-secure

- hosts: be1
  become: true
  vars:
  - dns_type: slave
  - bfdneigh:
    - {ip: "10.4.4.254"}
  - interfaces:
    - {device: "enp0s9.4", ip: "10.4.4.10", net: "10.4.4.0", prefix: 24, vlan: 4, area: 1, bfd: yes}
    - {device: "dummy0", ip: "10.99.99.1", net: "10.99.99.0", prefix: 24, area: 1 }
  roles:
  - networking
  - bird
  - named

- hosts: be2
  become: true
  vars:
  - dns_type: slave
  - bfdneigh:
    - {ip: "10.4.4.254"}
  - interfaces:
    - {device: "enp0s9.4", ip: "10.4.4.20", net: "10.4.4.0", prefix: 24, vlan: 4, area: 1 , bfd: yes}
    - {device: "dummy0", ip: "10.99.99.1", net: "10.99.99.0", prefix: 24, area: 1 }
  roles:
  - networking
  - bird
  - named

