- hosts: all
  gather_facts: yes
  roles:
    - common


- hosts: dummy
  roles:
    - dummy

- hosts: routers
  roles:
    - forward

- hosts: r0
  vars:
  - interfaces: 
    - {device: "eth2.2", ip: "10.2.2.1", prefix: 24, vlan: 2, area: 0 }
  roles:
  - networking
  - edgefw

- hosts: r1
  vars:
  - interfaces: 
    - {device: "eth2.2", ip: "10.2.2.254", prefix: 24, vlan: 2, area: 0 }
    - {device: "eth3.4", ip: "10.4.4.254", prefix: 24, vlan: 4, area: 1 }
  roles:
  - networking

- hosts: be1
  vars:
  - interfaces:
    - {device: "eth2.4", ip: "10.4.4.10", prefix: 24, vlan: 4, area: 1 }
    - {device: "dummy0", ip: "10.99.99.1", prefix: 24, area: 1 }

  roles:
  - networking

- hosts: be2
  vars:
  - interfaces:
    - {device: "eth2.4", ip: "10.4.4.20", prefix: 24, vlan: 4, area: 1 }
    - {device: "dummy0", ip: "10.99.99.1", prefix: 24, area: 1 }
  roles:
  - networking


