- hosts: dummy
  roles:
    - dummy

- hosts: routers
  roles:
    - forward

- hosts: r0
  vars:
  - interfaces:
    - device: eth2.2
      ip: 10.2.2.1
      prefix: 24
      vlan: 2
  roles:
  - role: networking


- hosts: r1
  roles:
  - role: networking
    interfaces:
      - device: eth2.2
        ip: 10.2.2.254
        prefix: 24
        net: 10.2.2.0
        vlan: 2

      - device: eth3.4
        ip: 10.4.4.254
        prefix: 24
        net: 10.4.4.0
        vlan: 4

- hosts: be1
  roles:
  - role: networking
    interfaces:
      - device: eth2.4
        ip: 10.4.4.10
        prefix: 24
        vlan: 4
      - device: dummy0
        ip: 10.99.99.1
        prefix: 24
        dummy: yes

- hosts: be2
  roles:
  - role: networking
    interfaces:
      - device: eth2.4
        ip: 10.4.4.20
        prefix: 24
        vlan: 4
      - device: dummy0
        ip: 10.99.99.1
        prefix: 24
        dummy: yes

