---
- name: Download openbfdf sources
  get_url:
    url: http://cdn.dyn.com/OpenBFDD/openbfdd-0.5.3.tar.gz
    dest: /tmp/openbfdd-0.5.3.tar.gz
    mode: 0644 
    timeout: 120 #wait 120 sec for convergence
  tags: openbfdd

- name: Unarchive openbfdd.tar.gz
  unarchive:
    src: /tmp/openbfdd-0.5.3.tar.gz
    dest: /tmp
    remote_src: yes
  tags: openbfdd

- name: Install dev tools
  yum: name={{ item }} state=present
  with_items:
  - make
  - gcc
  - gcc-c++
  tags: openbfdd

- name: Configure make and install openbfdd
  command: '{{ item }}'
  args:
    chdir: '/tmp/openbfdd-0.5.3'
  with_items:
  - "./configure --enable-silent-rules"
  - "make"
  - "make install"
  tags: openbfdd

- name: Create openbfdd.conf
  template: src=templates/openbfdd.conf.j2 dest=/etc/openbfdd.conf mode=0644 owner=root group=root
  tags: openbfdd

- name: Create openbfdd.service
  template: src=templates/openbfdd.service.j2 dest=/etc/systemd/system/openbfdd.service mode=0644 owner=root group=root
  tags: openbfdd

- name: Start openbfdd
  systemd: state=started name=openbfdd daemon_reload=yes
  tags: openbfdd