---
- name: install openldap client packets
  yum: name={{ item }} state=installed
  with_items: 
  - nss-pam-ldapd
  - openldap-clients
  - openssl
  tags: openldap-client

- name: Enable nslcd
  systemd: name=nslcd state=started enabled=yes
  tags: openldap-client


- name: Create cacert dir
  file: 
    path: /etc/openldap/cacerts/
    state: directory
    owner: root
    group: root
    mode: 0644
  tags: openldap-client
  
- name: Get and install LDAP cert ()
  shell: 'echo -n | openssl s_client -connect 127.0.0.1:636 | sed -ne "/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p" > /etc/openldap/cacerts/cert.pem'
  args:
    creates: /etc/openldap/cacerts/cert.pem
  tags: openldap-client

- name: Restore context
  shell: 'restorecon /etc/openldap/cacerts/cert.pem'
  tags: openldap-client

- name: Disable cert check
  lineinfile: 
    path: /etc/nslcd.conf
    regexp: '^tls_reqcert'
    insertafter: EOF
    line: 'tls_reqcert never'
  notify:
    restart nslcd
  tags: openldap-client


- name: Enable LDAP auth
  shell: 'authconfig --enableldap --enableldapauth --ldapserver={{ openldap_server }} --ldapbasedn=dc={{ openldap_domain.split(".")[0] }},dc={{ openldap_domain.split(".")[1] }} --enableldaptls --enablemkhomedir --enablemkhomedir --updateall; sleep 10'
  notify:
    restart nslcd
  tags: openldap-client, test

##- name: Sleep while service UP
##  shell: 'sleep 10'
##  tags: openldap-client
