- name: remove default route created with vagrant
  become: true
  lineinfile: dest=/etc/sysconfig/network-scripts/ifcfg-eth0
              regexp=''
              insertafter=EOF
              line='DEFROUTE=no'
  notify:
  - restart network

- name: Enable bird
  become: true
  systemd: name=bird state=started enabled=yes
  
- name: Create Bird config
  become: true
  template: src=templates/bird.j2 dest=/etc/bird.conf mode=0644 owner=root group=root
  notify:
  - restart bird



