---
- name: Disable Zero Configuration Network
  lineinfile: dest=/etc/sysconfig/network
              regexp=''
              insertafter=EOF
              line='NOZEROCONF=yes'
  notify:
  - restart network
  tags: networking

- name: Disable NetworkManager
  systemd: name=NetworkManager state=stopped enabled=no
  tags: networking

- name: Create vlan and dummy interfaces
  template: src=templates/ifcfg.j2 dest=/etc/sysconfig/network-scripts/ifcfg-{{ item.device }} mode=0644 owner=root group=root
  with_items:
  - "{{ network[ansible_hostname].interfaces }}"
  notify:
  - restart network
  tags: networking

# - name: Restart network
#   systemd: name=network state=restarted
#   tags: networking

- name: Disable Firewalld
  systemd: name=firewalld state=stopped enabled=no
  register: result
  tags: networking
# - name: check if killed
#   debug: msg="{{ killed.changed }}"