- hosts: all
  user: vagrant
  sudo: yes
  
  tasks:
    - name: Disable NetworkManager and firewalld
      
      systemd: name={{ item }} state=stopped enabled=no
      
      with_items:
        - NetworkManager
        - firewalld