---
- name: restart bird
  systemd: 
    name: bird
    state: restarted

- name: restart network
  service: name=network state=restarted
  
#- name: kill dhclient
#  command: pkill dhclient
#  listen: "restart network"

