---
- name: restart bird
  systemd: 
    name: bird
    state: restarted

- name: restart network service
  service: name=ospfd state=restarted
  listen: "restart network"

- name: kill dhclient
  command: pkill dhclient
  listen: "restart network"

