---
- name: restart network service
  service: name=ospfd state=restarted
  listen: "restart network"

- name: kill dhclient
  command: pkill dhclient
  listen: "restart network"

- name: save rules
  command: /usr/libexec/iptables/iptables.init save 
