---
- name: Install bacula direrctor components
  yum: name={{ item }} state=installed
  with_items:
  - graphite-web
  - python-carbon
  - httpd
  - libapache2-mod-wsgi
  tags: graphite

- name: Create graphite user
  mysql_user: login_user=root
              login_password="{{ password.mariadb.root }}"
              check_implicit_admin=yes
              name=graphite
              password={{ password.mariadb.graphite  }}
  tags: graphite

- name: Create a graphite DB
  mysql_db:
    login_user: root
    login_password: "{{ password.mariadb.root }}"
    name: "{{ graphite.db_name }}"
    state: present
  register: db_created
  tags: graphite

- name: Grant user rights
  mysql_user: login_user=root
              login_password="{{ password.mariadb.root }}"
              name="{{ graphite.db_user }}"
              priv="{{ graphite.db_name }}.*:ALL"
              state=present
  tags: graphite


- name: Deploy graphite configs
  template: src={{ item.j2 }} dest={{ item.dst }} owner={{ item.owner }} group={{ item.group }} mode=0644 backup=yes
  with_items:
  - {j2: "templates/local_settings.py.j2", dst: "/etc/graphite-web/local_settings.py", owner: "root", group: "root"}
  - {j2: "templates/graphite.conf.j2", dst: "/etc/httpd/conf.d/graphite.conf", owner: "root", group: "root"}
  notify: 
    - restart grpahite
    - restart httpd
  tags: graphite

- name: Setup the Graphite Web database
  shell: "/usr/lib/python2.7/site-packages/graphite/manage.py syncdb --noinput" 
  tags: graphite
  register: initdb

- debug: msg={{ initdb }}
  tags: graphite

- name: Enable httpd
  systemd: name=httpd state=started enabled=true
  tags: graphite

## - name: Enable graphite server (carbon)
##   systemd: name=carbon-cache state=started enabled=yes
##   tags: graphite