---
- name: Check if EPEL exists
  stat: path={{ epel_repofile_path }}
  register: epel_result
  tags: epel, common

- name: Install EPEL 
  yum:
    name: "{{ epel_repo_url }}"
    state: present
  register: result
  when: not epel_result.stat.exists
  tags: epel, common 

- name: Import EPEL GPG
  rpm_key:
    key: "{{ epel_repo_gpg_key_url }}"
    state: present
  when: not epel_result.stat.exists
  tags: epel, common 
  
- name: Install Bird, Quagga
  yum:
    name: "{{ item }}"
    state: present
  with_items:
  - bird
  - quagga
  - tcpdump
  tags: common
  
- name: Deploy knock scrpits
  template: src=templates/knock.j2 dest=/usr/local/bin/knock.sh mode=0744 owner=vagrant group=vagrant
  tags: common, knock
