---
- name: Install pip
  yum: 
    name: python-pip 
    state: present
  tags: secure-top

- name: Install python-pam module
  pip: 
    name: python-pam
    umask: "0022"
  tags: secure-top

- name: Deploy pam module
  template: src=templates/mypam.j2 dest=/etc/pam.d/mypam mode=0644 owner=root group=root
  tags: secure-top


- name: Deploy script
  template: src=templates/top.py.j2 dest=/usr/local/bin/top mode=4755 owner=root group=root
  tags: secure-top

- name: Add line to etc/profile
  lineinfile: 
    path: /etc/profile
    regexp: '^account.*required.*pam_script.so'
    insertafter: EOF
    line: "alias top='/usr/local/bin/top'"
  tags: secure-top

- name: Lock top
  file:
    path: /usr/bin/top
    mode: 0744
  tags: secure-top