
- name: Disable NetworkManager and firewalld
  systemd: name={{ item }} state=stopped enabled=no
  with_items:
    - NetworkManager
    - firewalld
  become: true

- name: enable ip_forward
  sysctl: 
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes
    state: present
    reload: yes
  become: true
  when: ipforward|lower == "yes"

- name: enable dummy
  modprobe:
    name: dummy
    state: present
    params: 'numdummies=1'
  become: true
  when: dummy|lower == "yes"

- name: host
  debug: msg="{{ item[0] }} == {{ item[1] }}" 
  with_items:
  - "{{ vlans }}"