
- name: Disable NetworkManager and firewalld
  become: true
  systemd: name={{ item }} state=stopped enabled=no
  with_items:
    - NetworkManager
    - firewalld

- name: host
  debug: msg="{{ item[0] }} == {{ item[1] }}" 
  with_items:
  - "{{ ifs }}"

- name: Pushes vlans
  become: true
  template: src=templates/ifcfg.j2 dest=/etc/sysconfig/network-scripts/ifcfg-{{ item[0] }} mode=0644 owner=root group=root
  with_items:
  - "{{ ifs }}"
  notify:
  - restart network


